### ISSUE TITLE
OSError, file too short

### ISSUE THREAD

**Issue by tleb** [Loodoor/UnamedPy#1]
```bash
$ git clone https://github.com/Loodoor/UnamedPy/
$ cd UnamedPy
$ pew new -a . unamed
$ python -V
Python 3.5.2
$ pip install pygame
$ sh launcher.sh
```

```
[FMODEX] Loading : ../assets/lib/libfmodex64.so
[FMODEX] Exists  : True
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from constantes import *
  File "/home/tleb/sd/Prog/python/UnamedPy/src/constantes.py", line 7, in <module>
    import ree
  File "/home/tleb/sd/Prog/python/UnamedPy/src/ree.py", line 7, in <module>
    import pyfmodex as fmod
  File "/home/tleb/sd/Prog/python/UnamedPy/src/pyfmodex/__init__.py", line 2, in <module>
    from .fmodex import get_debug_level, set_debug_level, get_disk_busy, set_disk_busy, get_memory_stats
  File "/home/tleb/sd/Prog/python/UnamedPy/src/pyfmodex/fmodex.py", line 32, in <module>
    _dll = CDLL('../assets/lib/libfmodex64.so')
  File "/usr/lib64/python3.5/ctypes/__init__.py", line 342, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ../assets/lib/libfmodex64.so: file too short
```

**Comment by Loodoor** [comment]
Bonsoir !

Un des gros problèmes de ce vieux projet (plus maintenu désormais) est que je n'ai jamais pu le tester sous linux. Le problème que tu as viens de la lib utilisée pour le son, fmodex. Les binaires que j'ai obtenu pour les systèmes unix doivent être out-dated ou bien ne correspondent pas à ta plateforme hélas :(

**Comment by tleb** [comment]
En fait, je voulais tester le plus récent. *J'arrive sur l'autre*.

**Comment by Loodoor** [comment]
Ben celui ci, comme indiqué dans les notes de release de unamed rebirth, c'est la première version x)
